from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from unittest.mock import MagicMock

from devbot.github_client import GitHubIssue
from devbot.models import RepositoryConfig
from devbot.specification import gather_task_evidence, render_specification
from devbot.specification_validation import (
    AmbiguousSpecificationError,
    InvalidTaskNumberError,
    SpecificationLoadError,
    SpecificationNotFoundError,
    ValidationSeverity,
    render_validation_report,
    validate_specification_file,
    validate_specification_text,
)

# --------------------------------------------------------------------------
# A compact, hand-written skeleton that satisfies every SPV rule - used as
# the base for isolated per-rule fixtures. Deliberately much smaller than a
# real generator-rendered Specification (see the "canonical" tests below for
# that), so a single targeted edit can break exactly one rule at a time.
# --------------------------------------------------------------------------

_MINIMAL_VALID = """# Specification: Task 099 — Sample

## Provenance

- Task Issue: [#1](https://example.invalid/1)
- Task Contract: `tasks/099-sample.md`
- Generated by `devbot specification generate` from repository evidence only.

# Overview

## Goal

Sample goal.

## Scope

In scope: sample.

## Background

Sample background.

## Roadmap Context

Not specified in the Task Contract.

# Functional Requirements

## Required Behaviour

Sample behaviour.

## Acceptance Criteria

### CP-099-1 - sample

- sample criterion

## Out of Scope

Sample out of scope.

# Technical Design

## Architecture

Not specified in the Task Contract.

## Files Expected to Change

- `src/devbot/sample.py`

## Dependencies

Not specified in the Task Contract.

## Constraints

Not specified in the Task Contract.

## Migration Notes

Not specified in the Task Contract.

# Validation

## Required Tests and Quality Gates

### CP-099-1 - sample

- sample criterion

## Validation Commands

```bash
uv run pytest
```

## Success Criteria

Not specified in the Task Contract.

# Safety

## Things the Implementation Agent Must NOT Do

Sample restriction.

# Completion

## Expected Deliverables

Not specified in the Task Contract.

## Result Document

`results/099-sample.md`

## PR Expectations

Not specified in the Task Contract.

# Handoff

## Required Handoff Procedure

Not specified in the Task Contract.

## Token-Limit Behaviour

Not specified in the Task Contract.

# Full Task Contract Reference

```markdown
# Task 099: Sample

## Goal

Sample goal.
```
"""

_SPEC_PATH = Path("specifications/099-sample.md")


def _validate(text: str = _MINIMAL_VALID, task_number: int = 99):
    return validate_specification_text(text, task_number=task_number, specification_path=_SPEC_PATH)


def _codes(issues) -> list[str]:
    return [issue.code for issue in issues]


# --------------------------------------------------------------------------
# CP-043-1: the minimal skeleton itself, and a real generator-rendered
# Specification, both pass with no errors.
# --------------------------------------------------------------------------


def test_minimal_valid_skeleton_passes() -> None:
    result = _validate()

    assert result.passed is True
    assert result.errors == ()
    assert result.warnings == ()


def _repository(**overrides: object) -> RepositoryConfig:
    defaults: dict[str, object] = dict(
        owner="someone",
        repo="myrepo",
        enabled=True,
        local_path=Path("/tmp/nonexistent-devbot-repo"),
        default_branch="main",
    )
    defaults.update(overrides)
    return RepositoryConfig(**defaults)  # type: ignore[arg-type]


def _issue(number: int, title: str, body: str = "") -> GitHubIssue:
    return GitHubIssue(
        repository="someone/myrepo",
        number=number,
        title=title,
        body=body,
        state="open",
        labels=(),
        created_at=datetime(2026, 7, 18, tzinfo=UTC),
    )


_GENERATOR_CONTRACT = """# Task 099: Sample Task Marker Zebra

## Goal

Distinctive goal text marker QUOKKA.

## In Scope

- distinctive scope item NARWHAL

## Out of Scope

- distinctive out-of-scope item PLATYPUS

## Functional Requirements

1. distinctive requirement marker AXOLOTL

## Quality Gates

### CP-099-1 - marker

Required tests:
- `test_marker_pangolin`

## Validation Gate

```bash
uv run pytest
```

## Files Expected to Change

- `src/devbot/sample.py`

## Risk

- distinctive risk marker OKAPI

## Definition of Done

- distinctive done marker CAPYBARA

## Git Rules

- Task Issue: #99
"""


def _render_canonical_specification(tmp_path: Path) -> str:
    tasks_dir = tmp_path / "tasks"
    tasks_dir.mkdir()
    (tasks_dir / "099-sample.md").write_text(_GENERATOR_CONTRACT, encoding="utf-8")
    client = MagicMock()
    client.list_issues.return_value = [_issue(1, "Task 099: Sample Task Marker Zebra")]
    evidence = gather_task_evidence(client, _repository(), 99, tasks_dir=tasks_dir)
    return render_specification(evidence)


def test_canonical_generator_output_passes(tmp_path: Path) -> None:
    content = _render_canonical_specification(tmp_path)

    result = validate_specification_text(content, task_number=99, specification_path=_SPEC_PATH)

    assert result.passed is True
    assert result.errors == ()
    assert result.warnings == ()


def test_repeated_validation_of_identical_bytes_is_equivalent() -> None:
    first = _validate()
    second = _validate()

    assert first == second


# --------------------------------------------------------------------------
# CP-043-2: file resolution (operational failures, not document failures)
# --------------------------------------------------------------------------


def test_invalid_task_number_raises_for_zero_and_negative(tmp_path: Path) -> None:
    for bad_number in (0, -1):
        try:
            validate_specification_file(tmp_path, bad_number)
        except InvalidTaskNumberError:
            continue
        raise AssertionError(f"expected InvalidTaskNumberError for {bad_number}")


def test_missing_specification_raises(tmp_path: Path) -> None:
    (tmp_path / "specifications").mkdir()

    try:
        validate_specification_file(tmp_path, 99)
        raise AssertionError("expected SpecificationNotFoundError")
    except SpecificationNotFoundError:
        pass


def test_missing_specifications_directory_raises(tmp_path: Path) -> None:
    try:
        validate_specification_file(tmp_path, 99)
        raise AssertionError("expected SpecificationNotFoundError")
    except SpecificationNotFoundError:
        pass


def test_ambiguous_specification_raises_when_multiple_files_match(tmp_path: Path) -> None:
    directory = tmp_path / "specifications"
    directory.mkdir()
    (directory / "099-sample-a.md").write_text(_MINIMAL_VALID, encoding="utf-8")
    (directory / "099-sample-b.md").write_text(_MINIMAL_VALID, encoding="utf-8")

    try:
        validate_specification_file(tmp_path, 99)
        raise AssertionError("expected AmbiguousSpecificationError")
    except AmbiguousSpecificationError:
        pass


def test_unreadable_specification_raises_load_error(tmp_path: Path) -> None:
    directory = tmp_path / "specifications"
    directory.mkdir()
    # A directory matching the glob pattern is "found" but cannot be read as
    # text - a portable, permission-independent way to trigger an I/O error.
    (directory / "099-broken.md").mkdir()

    try:
        validate_specification_file(tmp_path, 99)
        raise AssertionError("expected SpecificationLoadError")
    except SpecificationLoadError:
        pass


def test_validate_specification_file_end_to_end_passes(tmp_path: Path) -> None:
    directory = tmp_path / "specifications"
    directory.mkdir()
    (directory / "099-sample.md").write_text(_MINIMAL_VALID, encoding="utf-8")

    result = validate_specification_file(tmp_path, 99)

    assert result.passed is True
    assert result.specification_path == directory / "099-sample.md"


# --------------------------------------------------------------------------
# CP-043-3: SPV-001 canonical title
# --------------------------------------------------------------------------


def test_malformed_title_fails() -> None:
    text = _MINIMAL_VALID.replace(
        "# Specification: Task 099 — Sample", "# Not A Canonical Title"
    )
    result = _validate(text)

    assert result.passed is False
    assert "SPV-001" in _codes(result.errors)


def test_title_task_number_mismatch_fails() -> None:
    text = _MINIMAL_VALID.replace(
        "# Specification: Task 099 — Sample", "# Specification: Task 100 — Sample"
    )
    result = _validate(text, task_number=99)

    assert result.passed is False
    assert "SPV-001" in _codes(result.errors)


def test_empty_title_fails() -> None:
    text = _MINIMAL_VALID.replace(
        "# Specification: Task 099 — Sample", "# Specification: Task 099 — "
    )
    result = _validate(text)

    assert result.passed is False
    assert "SPV-001" in _codes(result.errors)


def test_canonical_title_passes() -> None:
    result = _validate()

    assert "SPV-001" not in _codes(result.errors)


# --------------------------------------------------------------------------
# CP-043-3/SPV-002: Provenance
# --------------------------------------------------------------------------


def test_missing_provenance_fails() -> None:
    text = _MINIMAL_VALID.replace(
        "## Provenance\n\n"
        "- Task Issue: [#1](https://example.invalid/1)\n"
        "- Task Contract: `tasks/099-sample.md`\n"
        "- Generated by `devbot specification generate` from repository evidence only.\n\n",
        "",
    )
    result = _validate(text)

    assert result.passed is False
    assert "SPV-002" in _codes(result.errors)


def test_incomplete_provenance_fails() -> None:
    text = _MINIMAL_VALID.replace(
        "- Task Contract: `tasks/099-sample.md`\n", ""
    )
    result = _validate(text)

    assert result.passed is False
    assert "SPV-002" in _codes(result.errors)


# --------------------------------------------------------------------------
# CP-043-4/SPV-003: required top-level sections (missing/duplicated)
# --------------------------------------------------------------------------


def test_missing_required_top_level_section_fails() -> None:
    text = _MINIMAL_VALID.replace(
        "# Safety\n\n## Things the Implementation Agent Must NOT Do\n\nSample restriction.\n\n",
        "",
    )
    result = _validate(text)

    assert result.passed is False
    assert any(
        issue.code == "SPV-003" and issue.section == "# Safety" for issue in result.errors
    )


def test_duplicated_required_top_level_section_fails() -> None:
    text = _MINIMAL_VALID.replace(
        "# Functional Requirements",
        "# Overview\n\n## Goal\n\nDuplicate.\n\n# Functional Requirements",
        1,
    )
    result = _validate(text)

    assert result.passed is False
    assert any(
        issue.code == "SPV-003" and issue.section == "# Overview" for issue in result.errors
    )


# --------------------------------------------------------------------------
# CP-043-4/SPV-004: required subsections
# --------------------------------------------------------------------------


def test_missing_required_subsection_fails() -> None:
    text = _MINIMAL_VALID.replace("## Background\n\nSample background.\n\n", "")
    result = _validate(text)

    assert result.passed is False
    assert any(issue.code == "SPV-004" and issue.section == "Overview" for issue in result.errors)


# --------------------------------------------------------------------------
# CP-043-4/SPV-005: empty required body (fallback counts as content)
# --------------------------------------------------------------------------


def test_empty_required_subsection_body_fails() -> None:
    text = _MINIMAL_VALID.replace("## Background\n\nSample background.\n\n", "## Background\n\n")
    result = _validate(text)

    assert result.passed is False
    assert any(issue.code == "SPV-005" and issue.section == "Background" for issue in result.errors)


def test_not_specified_fallback_counts_as_content() -> None:
    # `_MINIMAL_VALID` already uses the literal fallback for several
    # subsections (Roadmap Context, Architecture, Dependencies, ...) and
    # passes cleanly - none of them should trigger SPV-005.
    result = _validate()

    assert "SPV-005" not in _codes(result.errors)


# --------------------------------------------------------------------------
# CP-043-5/SPV-006: Acceptance Criteria
# --------------------------------------------------------------------------


def test_acceptance_criteria_checkpoint_form_passes() -> None:
    result = _validate()

    assert "SPV-006" not in _codes(result.errors)


def test_acceptance_criteria_checklist_form_passes() -> None:
    text = _MINIMAL_VALID.replace(
        "## Acceptance Criteria\n\n### CP-099-1 - sample\n\n- sample criterion\n\n",
        "## Acceptance Criteria\n\n- [ ] sample checklist criterion\n\n",
    )
    result = _validate(text)

    assert "SPV-006" not in _codes(result.errors)


def test_acceptance_criteria_list_form_passes() -> None:
    text = _MINIMAL_VALID.replace(
        "## Acceptance Criteria\n\n### CP-099-1 - sample\n\n- sample criterion\n\n",
        "## Acceptance Criteria\n\n1. sample numbered criterion\n\n",
    )
    result = _validate(text)

    assert "SPV-006" not in _codes(result.errors)


def test_empty_acceptance_criteria_fails() -> None:
    text = _MINIMAL_VALID.replace(
        "## Acceptance Criteria\n\n### CP-099-1 - sample\n\n- sample criterion\n\n",
        "## Acceptance Criteria\n\nNot specified in the Task Contract.\n\n",
    )
    result = _validate(text)

    assert result.passed is False
    assert any(
        issue.code == "SPV-006" and issue.section == "Acceptance Criteria"
        for issue in result.errors
    )


def test_duplicate_checkpoint_identifiers_fail() -> None:
    text = _MINIMAL_VALID.replace(
        "## Acceptance Criteria\n\n### CP-099-1 - sample\n\n- sample criterion\n\n",
        "## Acceptance Criteria\n\n### CP-099-1 - sample\n\n### CP-099-1 - duplicate\n\n",
    )
    result = _validate(text)

    assert result.passed is False
    assert any(
        issue.code == "SPV-006" and "duplicate checkpoint identifier" in issue.message
        for issue in result.errors
    )


# --------------------------------------------------------------------------
# CP-043-6/SPV-007: Validation Commands
# --------------------------------------------------------------------------


def test_validation_commands_with_command_passes() -> None:
    result = _validate()

    assert "SPV-007" not in _codes(result.errors)


def test_validation_commands_not_specified_fallback_passes() -> None:
    text = _MINIMAL_VALID.replace(
        "## Validation Commands\n\n```bash\nuv run pytest\n```\n\n",
        "## Validation Commands\n\nNot specified in the Task Contract.\n\n",
    )
    result = _validate(text)

    assert "SPV-007" not in _codes(result.errors)


def test_empty_validation_commands_fails() -> None:
    text = _MINIMAL_VALID.replace(
        "## Validation Commands\n\n```bash\nuv run pytest\n```\n\n",
        "## Validation Commands\n\n",
    )
    result = _validate(text)

    assert result.passed is False
    assert any(
        issue.code == "SPV-007" and issue.section == "Validation Commands"
        for issue in result.errors
    )


# --------------------------------------------------------------------------
# CP-043-6/SPV-008: Safety boundary
# --------------------------------------------------------------------------


def test_safety_boundary_with_content_passes() -> None:
    result = _validate()

    assert "SPV-008" not in _codes(result.errors)


def test_empty_safety_boundary_fails() -> None:
    text = _MINIMAL_VALID.replace(
        "## Things the Implementation Agent Must NOT Do\n\nSample restriction.\n\n",
        "## Things the Implementation Agent Must NOT Do\n\n",
    )
    result = _validate(text)

    assert result.passed is False
    assert any(
        issue.code == "SPV-008" and issue.section == "Things the Implementation Agent Must NOT Do"
        for issue in result.errors
    )


# --------------------------------------------------------------------------
# CP-043-7/SPV-009: Contract traceability
# --------------------------------------------------------------------------


def test_full_contract_reference_with_content_passes() -> None:
    result = _validate()

    assert "SPV-009" not in _codes(result.errors)


def test_empty_full_contract_reference_fails() -> None:
    text = _MINIMAL_VALID.replace(
        "# Full Task Contract Reference\n\n"
        "```markdown\n# Task 099: Sample\n\n## Goal\n\nSample goal.\n```\n",
        "# Full Task Contract Reference\n\n",
    )
    result = _validate(text)

    assert result.passed is False
    assert any(
        issue.code == "SPV-009" and issue.section == "Full Task Contract Reference"
        for issue in result.errors
    )


def test_path_only_full_contract_reference_fails() -> None:
    text = _MINIMAL_VALID.replace(
        "# Full Task Contract Reference\n\n"
        "```markdown\n# Task 099: Sample\n\n## Goal\n\nSample goal.\n```\n",
        "# Full Task Contract Reference\n\nSee `tasks/099-sample.md`.\n",
    )
    result = _validate(text)

    assert result.passed is False
    assert any(
        issue.code == "SPV-009" and issue.section == "Full Task Contract Reference"
        for issue in result.errors
    )


# --------------------------------------------------------------------------
# CP-043-8/SPV-010/011/012: warnings
# --------------------------------------------------------------------------


def test_out_of_order_top_level_sections_warns_but_still_passes() -> None:
    safety_block = (
        "# Safety\n\n## Things the Implementation Agent Must NOT Do\n\nSample restriction.\n\n"
    )
    technical_design_block = (
        "# Technical Design\n\n"
        "## Architecture\n\nNot specified in the Task Contract.\n\n"
        "## Files Expected to Change\n\n- `src/devbot/sample.py`\n\n"
        "## Dependencies\n\nNot specified in the Task Contract.\n\n"
        "## Constraints\n\nNot specified in the Task Contract.\n\n"
        "## Migration Notes\n\nNot specified in the Task Contract.\n\n"
    )
    # Move Safety before Technical Design - both remain present and complete.
    text = _MINIMAL_VALID.replace(technical_design_block, "").replace(
        safety_block, safety_block + technical_design_block
    )

    result = _validate(text)

    assert result.passed is True
    assert "SPV-010" in _codes(result.warnings)


def test_unknown_top_level_section_warns_but_still_passes() -> None:
    text = _MINIMAL_VALID.replace(
        "# Full Task Contract Reference",
        "# Extra Notes\n\nSomething not in the canonical schema.\n\n# Full Task Contract Reference",
    )
    result = _validate(text)

    assert result.passed is True
    assert any(
        issue.code == "SPV-011" and issue.section == "Extra Notes" for issue in result.warnings
    )


def test_unresolved_todo_marker_warns_but_still_passes() -> None:
    text = _MINIMAL_VALID.replace("Sample background.", "Sample background. TODO: fill in more.")
    result = _validate(text)

    assert result.passed is True
    assert any(issue.code == "SPV-012" for issue in result.warnings)


def test_not_specified_fallback_is_not_an_unresolved_marker() -> None:
    result = _validate()

    assert "SPV-012" not in _codes(result.warnings)


def test_marker_inside_full_contract_reference_is_not_flagged() -> None:
    text = _MINIMAL_VALID.replace(
        "```markdown\n# Task 099: Sample\n\n## Goal\n\nSample goal.\n```",
        "```markdown\n# Task 099: Sample\n\n## Goal\n\nTODO: historical Contract text.\n```",
    )
    result = _validate(text)

    assert "SPV-012" not in _codes(result.warnings)


def test_cli_placeholder_angle_brackets_are_not_flagged_as_unresolved() -> None:
    text = _MINIMAL_VALID.replace(
        "Sample behaviour.", "Run `devbot specification generate --task <N>`."
    )
    result = _validate(text)

    assert "SPV-012" not in _codes(result.warnings)


def test_warnings_alone_do_not_fail_validation() -> None:
    text = _MINIMAL_VALID.replace("Sample background.", "Sample background. TODO: expand.")
    result = _validate(text)

    assert result.warnings != ()
    assert result.errors == ()
    assert result.passed is True


# --------------------------------------------------------------------------
# CP-043-8/SPV-013: deterministic issue ordering
# --------------------------------------------------------------------------


def test_issues_are_ordered_by_line_then_code_then_message() -> None:
    text = _MINIMAL_VALID.replace(
        "## Background\n\nSample background.\n\n", "## Background\n\n"
    ).replace(
        "## Things the Implementation Agent Must NOT Do\n\nSample restriction.\n\n",
        "## Things the Implementation Agent Must NOT Do\n\n",
    )
    result = _validate(text)

    lines = [issue.line for issue in result.errors if issue.line is not None]
    assert lines == sorted(lines)


def test_severity_never_mixed_between_errors_and_warnings_tuples() -> None:
    text = _MINIMAL_VALID.replace("Sample background.", "Sample background. TODO: expand.")
    result = _validate(text)

    assert all(issue.severity is ValidationSeverity.ERROR for issue in result.errors)
    assert all(issue.severity is ValidationSeverity.WARNING for issue in result.warnings)


# --------------------------------------------------------------------------
# CP-043-9: report rendering
# --------------------------------------------------------------------------


def test_render_text_report_shows_pass() -> None:
    result = _validate()

    report = render_validation_report(result, output_format="text")

    assert "result: PASS" in report
    assert "099" in report


def test_render_text_report_shows_failed_and_errors() -> None:
    text = _MINIMAL_VALID.replace(
        "## Background\n\nSample background.\n\n", "## Background\n\n"
    )
    result = _validate(text)

    report = render_validation_report(result, output_format="text")

    assert "result: FAILED" in report
    assert "SPV-005" in report


def test_render_json_report_is_valid_and_deterministic() -> None:
    import json

    result = _validate()

    first = render_validation_report(result, output_format="json")
    second = render_validation_report(result, output_format="json")

    assert first == second
    payload = json.loads(first)
    assert payload["task_number"] == 99
    assert payload["passed"] is True
    assert payload["errors"] == []
    assert payload["warnings"] == []


def test_render_json_report_includes_issue_fields() -> None:
    import json

    text = _MINIMAL_VALID.replace(
        "## Background\n\nSample background.\n\n", "## Background\n\n"
    )
    result = _validate(text)

    payload = json.loads(render_validation_report(result, output_format="json"))

    assert payload["passed"] is False
    assert any(issue["code"] == "SPV-005" for issue in payload["errors"])
    for issue in payload["errors"]:
        assert set(issue.keys()) == {"code", "severity", "message", "section", "line"}
